#background {
#    path = screenshot
#    blur_passes = 3
#    blur_size = 8
#}

#input-field {
#    size = 200, 50
#    position = 0, -80
#    monitor =
#    dots_center = true
#    fade_on_empty = true
#    outline_thickness = 2
#    placeholder_text = <i>Password...</i>
#}

#label {
#    text = $TIME
#    font_size = 64
#    position = 0, 80
#    halign = center
#    valign = center
#}

general {
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = /home/laxerem/Images/wallpaper/wall1.png
    blur_passes = 3
    blur_size = 2
    noise = 0.02
    contrast = 1.1
    brightness = 0.9
}

input-field {
    monitor =
    size = 280, 56
    position = 0, -100
    halign = center
    valign = center

    fade_on_empty = true
    dots_center = true
    dots_size = 0.3
    dots_spacing = 0.4

    rounding = 12
    outline_thickness = 2

    outer_color = rgba(255, 255, 255, 60)
    inner_color = rgba(0, 0, 0, 120)
    font_color  = rgba(255, 255, 255, 230)

    placeholder_text = <i>Enter Password</i>
    font_family = monospace

    shadow_passes = 2
    shadow_size = 6

    animation {
        enabled = true
        duration = 150
        curve = ease_out
    }
}

label {
    monitor =
    text = $TIME
    font_size = 72
    font_family = monospace
    position = 0, 120
    halign = center
    valign = center
    color = rgba(255, 255, 255)
    shadow_passes = 2
    shadow_size = 4
}

label {
    monitor =
    text = cmd[date +"%A, %d %B"]
    font_size = 18
    position = 0, 70
    halign = center
    valign = center
    color = rgba(255, 255, 255, 160)
}
