$lock_bg = /home/laxerem/.config/hypr/wallpapers/61f4b81a3b42c08f316f3c7f9792aed5.jpg
$lock_fx = dust
$lock_text_font = Montserrat Ultra-Light 16
$lock_text_speed = 89
$lock_text_anim = fade
$lock_text_hold = 7
$lock_text_gap = 4
